// カテゴリ定義・マッピング
const majorCategories = [
    { code: 'MAIN_STORY_PART1', name: '第一部メインストーリー'},
    { code: 'MAIN_STORY_PART2', name: '第二部メインストーリー'},
    { code: 'MAIN_STORY_PART3', name: '第三部メインストーリー'},
    { code: 'MAIN_STORY_PART4', name: '第四部メインストーリー'},
    { code: 'MAIN_STORY_PART5', name: '第五部メインストーリー'},
    { code: 'KIZUNA_NO_KISEKI', name: '絆の軌跡'},
    { code: 'DENSHO_HEN', name: '伝承篇'},
    { code: 'GRAND_SAGA', name: 'グランドサーガ'},
    { code: 'SECRET_QUEST', name: 'シークレットクエスト'},
    { code: 'SIDE_STORY_PART4', name: '第四部サイドストーリー'},
    { code: 'ANOMALY_QUEST', name: '異変クエスト'},
    { code: 'GAIDEN', name: '外伝'},
    { code: 'EVENT_TOUHA', name: '踏破型イベント'},
    { code: 'EVENT_DAISYURYO', name: '大狩猟戦イベント'},
    { code: 'EVENT_KYOTEKI', name: '脅敵襲来イベント'},
    { code: 'CHAIN_STORY', name: 'チェインストーリー'},
    { code: 'EVENT_QUEST', name: 'イベントクエスト'},
    { code: 'COLLAB_QUEST', name: 'コラボクエスト'},
    { code: 'COLLAB_GAIDEN', name: 'コラボ外伝'},
    { code: 'FREE_QUEST', name: 'フリークエスト'},
    { code: 'CHARACTER_QUEST', name: 'キャラクエ'},
    { code: 'OTHER', name: 'その他'}
];

const categoryMapping = {
    'MAIN_STORY_PART1': 1,
    'MAIN_STORY_PART2': 2,
    'MAIN_STORY_PART3': 3,
    'MAIN_STORY_PART4': 4,
    'MAIN_STORY_PART5': 5,
    'KIZUNA_NO_KISEKI': 6,
    'DENSHO_HEN': 7,
    'GRAND_SAGA': 8,
    'SECRET_QUEST': 9,
    'SIDE_STORY_PART4': 10,
    'ANOMALY_QUEST': 11,
    'GAIDEN': 12,
    'EVENT_TOUHA': 13,
    'EVENT_DAISYURYO': 14,
    'EVENT_KYOTEKI': 15,
    'CHAIN_STORY': 16,
    'EVENT_QUEST': 17,
    'COLLAB_QUEST': 18,
    'COLLAB_GAIDEN': 19,
    'FREE_QUEST': 20,
    'CHARACTER_QUEST': 21,
    'OTHER': 99
};
